import { TransactionCategory } from "../models/Transaction";

export const CategoryColorMap: Record<TransactionCategory, string> = {
  [TransactionCategory.Coffe]: "#8B5E3C",
  [TransactionCategory.Food]: "#4CAF50",
  [TransactionCategory.Transport]: "#2196F3",
  [TransactionCategory.Entertainment]: "#0D9488",
  [TransactionCategory.Utilities]: "#FF9800",
  [TransactionCategory.Shopping]: "#BE185D",
  [TransactionCategory.Health]: "#EF4444",
  [TransactionCategory.Education]: "#1E3A8A",
  [TransactionCategory.Travel]: "#0EA5E9",
  [TransactionCategory.Sports]: "#06B6D4",
  [TransactionCategory.Subscriptions]: "#A16207",
  [TransactionCategory.Savings]: "#14B8A6",
  [TransactionCategory.Investments]: "#10B981",
  [TransactionCategory.Gifts]: "#EC4899",
  [TransactionCategory.Love]: "#F43F5E",
  [TransactionCategory.Charity]: "#22C55E",
  [TransactionCategory.Other]: "#9E9E9E",
  [TransactionCategory.Salary]: "#15803D",
  [TransactionCategory.Bonus]: "#65A30D",
  [TransactionCategory.Freelance]: "#0F766E",
  [TransactionCategory.Business]: "#1D4ED8",
  [TransactionCategory.Interest]: "#3F6212",
  [TransactionCategory.Dividends]: "#0891B2",
  [TransactionCategory.RentalIncome]: "#475569",
  [TransactionCategory.Refund]: "#BE123C",
};
