name: Backend Build

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore KeepItSimple.sln

      - name: Run Format
        run: dotnet format --verify-no-changes

  Build:
    runs-on: ubuntu-latest
    needs: [Format]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore KeepItSimple.sln

      - name: Build backend
        run: dotnet build KeepItSimple.sln --configuration Release --no-restore
